services:

  backend-fastapi:
    build:
      context: backend-fastapi
      dockerfile: Dockerfile
    image: backend-fastapi-image:latest
    networks:
      - network-farmapp
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    env_file:
      - ./backend-fastapi/fastapi.env
    ports:
      - 8000:8000
    depends_on:
      - backend-mongodb
    develop: # for docker compose watch can be commented if not used
      watch:
        - action: sync
          path: backend-fastapi
          target: /app
        - action: rebuild
          path: requirements.txt
    container_name: fastapi
  
  backend-mongo-express:
    image: mongo-express
    networks:
      - network-farmapp
    ports:
      - 8081:8081
    env_file:
      - ./backend-mongo/mongoexpress.env
    depends_on:
      - backend-mongodb
    container_name: mongoexpress
  
  backend-mongodb:
    image: mongo
    networks:
      - network-farmapp
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    env_file:
      - ./backend-mongo/mongodb.env
    container_name: mongodb

  frontend-vite-react:
    build:
      context: frontend-vitereact
      dockerfile: Dockerfile
    image: frontend-react-image:latest
    networks:
      - network-farmapp
    ports:
      - 5173:5173
    env_file:
      - ./frontend-vitereact/vitereact.env
    depends_on:
      - backend-fastapi
    develop: # for docker compose watch can be commented if not used
      watch:
        - action: sync
          path: frontend/src
          target: /app/src
        - action: rebuild
          path: package.json
    container_name: frontend-vitereact

volumes:
  mongo-data:
  mongo-config:

networks:
  network-farmapp:
    name: network-farmapp
    driver: bridge